-- phase: 7
-- topic: labスキーマ作成 + テーブル定義（制約を一通り入れる）
-- dataset: ec-v1（同じDB内に lab スキーマを作る）
CREATE SCHEMA lab;

-- =========
-- 1) 顧客（UNIQUE / CHECK / DEFAULT / NOT NULL）
-- =========
CREATE TABLE lab.customer (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_lab_customer PRIMARY KEY (customer_id),
    CONSTRAINT uq_lab_customer_email UNIQUE (email),
    CONSTRAINT chk_lab_customer_status CHECK (status IN ('active', 'suspended')),
    CONSTRAINT chk_lab_customer_email_format CHECK (position('@' IN email) > 1)
);

COMMENT ON TABLE lab.customer IS '学習用：顧客。UNIQUE/CHECK/DEFAULTの基本を体験する。';

COMMENT ON COLUMN lab.customer.email IS 'メール（簡易チェックあり・一意）。';

-- =========
-- 2) 口座（FK / UNIQUE（複合） / CHECK / DEFAULT）
-- =========
CREATE TABLE lab.account (
    account_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'JPY',
    balance_yen BIGINT NOT NULL DEFAULT 0,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_lab_account PRIMARY KEY (account_id),
    CONSTRAINT fk_lab_account_customer FOREIGN KEY (customer_id) REFERENCES lab.customer (customer_id),
    CONSTRAINT uq_lab_account_customer_currency UNIQUE (customer_id, currency),
    CONSTRAINT chk_lab_account_currency CHECK (currency IN ('JPY', 'USD', 'EUR')),
    CONSTRAINT chk_lab_account_balance_nonneg CHECK (balance_yen >= 0)
);

COMMENT ON TABLE lab.account IS '学習用：口座。FKと複合UNIQUE、CHECKを体験する。';

-- FK列はインデックス推奨（PostgreSQLはFK作成だけでは自動でインデックスを貼らない）
CREATE INDEX idx_lab_account_customer_id ON lab.account (customer_id);

-- =========
-- 3) 振込（FK×2 / CHECK / UNIQUE / DEFAULT）
-- =========
CREATE TABLE lab.transfer (
    transfer_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    from_account_id INTEGER NOT NULL,
    to_account_id INTEGER NOT NULL,
    amount_yen BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'requested',
    idempotency_key TEXT NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_lab_transfer PRIMARY KEY (transfer_id),
    CONSTRAINT fk_lab_transfer_from FOREIGN KEY (from_account_id) REFERENCES lab.account (account_id),
    CONSTRAINT fk_lab_transfer_to FOREIGN KEY (to_account_id) REFERENCES lab.account (account_id),
    CONSTRAINT uq_lab_transfer_idempotency UNIQUE (idempotency_key),
    CONSTRAINT chk_lab_transfer_amount_pos CHECK (amount_yen > 0),
    CONSTRAINT chk_lab_transfer_status CHECK (status IN ('requested', 'completed', 'cancelled')),
    CONSTRAINT chk_lab_transfer_not_same CHECK (from_account_id <> to_account_id)
);

COMMENT ON TABLE lab.transfer IS '学習用：振込。FKが2本ある例。CHECK/UNIQUEも含む。';

CREATE INDEX idx_lab_transfer_from_account_id ON lab.transfer (from_account_id);

CREATE INDEX idx_lab_transfer_to_account_id ON lab.transfer (to_account_id);

CREATE INDEX idx_lab_transfer_requested_at ON lab.transfer (requested_at);

-- =========
-- 4) 注文（複合PKの題材：order_line）
-- =========
CREATE TABLE lab.simple_order (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL,
    order_status TEXT NOT NULL DEFAULT 'draft',
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_lab_simple_order PRIMARY KEY (order_id),
    CONSTRAINT fk_lab_simple_order_customer FOREIGN KEY (customer_id) REFERENCES lab.customer (customer_id),
    CONSTRAINT chk_lab_simple_order_status CHECK (
        order_status IN (
            'draft',
            'paid',
            'cancelled',
            'shipped',
            'delivered'
        )
    )
);

CREATE INDEX idx_lab_simple_order_customer_id ON lab.simple_order (customer_id);

CREATE INDEX idx_lab_simple_order_ordered_at ON lab.simple_order (ordered_at);

CREATE TABLE lab.simple_order_line (
    order_id INTEGER NOT NULL,
    line_no INTEGER NOT NULL,
    item_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price_yen INTEGER NOT NULL,
    CONSTRAINT pk_lab_simple_order_line PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_lab_simple_order_line_order FOREIGN KEY (order_id) REFERENCES lab.simple_order (order_id) ON DELETE CASCADE,
    CONSTRAINT chk_lab_simple_order_line_qty_pos CHECK (quantity > 0),
    CONSTRAINT chk_lab_simple_order_line_price_nonneg CHECK (unit_price_yen >= 0)
);

CREATE INDEX idx_lab_simple_order_line_order_id ON lab.simple_order_line (order_id);

COMMENT ON TABLE lab.simple_order_line IS '学習用：複合PK（order_id, line_no）とON DELETE CASCADEの例。';
