-- phase: 13
-- topic: 権限（ROLE / GRANT）練習用セットアップ
-- dataset: 任意（ops_lab を作ってそこで練習）
-- 方針:
--   - 既存publicは触らず、ops_labで完結させる
--   - ロールは「読み取り専用」「読み書き」「メンテ（DDL可）」を想定
--   - ログインユーザーは作らず、SET ROLE で体験する
-- 0) 作り直し（再実行対応）
DROP SCHEMA IF EXISTS ops_lab CASCADE;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'r_ops_readonly') THEN
    DROP ROLE r_ops_readonly;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'r_ops_rw') THEN
    DROP ROLE r_ops_rw;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'r_ops_ddl') THEN
    DROP ROLE r_ops_ddl;
  END IF;
END $$;

-- 1) スキーマ・テーブル作成
CREATE SCHEMA ops_lab;

CREATE TABLE ops_lab.sample_order (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('draft', 'paid', 'cancelled')),
    amount_yen BIGINT NOT NULL CHECK (amount_yen >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ops_lab.sample_order_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    action TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
    ops_lab.sample_order (user_id, status, amount_yen)
VALUES
    (1, 'draft', 1000),
    (2, 'paid', 2000),
    (3, 'paid', 1500);

-- 2) ロール作成
-- r_ops_readonly: SELECTだけ
-- r_ops_rw: SELECT + INSERT/UPDATE/DELETE
-- r_ops_ddl: DDLもできる（スキーマ作成など）
CREATE ROLE r_ops_readonly;

CREATE ROLE r_ops_rw;

CREATE ROLE r_ops_ddl;

-- 3) 権限付与（スキーマUSAGEが無いとテーブルが見えない点が重要）
GRANT USAGE ON SCHEMA ops_lab TO r_ops_readonly;

GRANT USAGE ON SCHEMA ops_lab TO r_ops_rw;

GRANT
SELECT
    ON ALL TABLES IN SCHEMA ops_lab TO r_ops_readonly;

GRANT
SELECT
,
    INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA ops_lab TO r_ops_rw;

-- 4) 新規作成テーブルにも自動で権限を付ける（実務で重要）
-- ※ “このユーザーが今後作成するもの” に適用される
ALTER DEFAULT PRIVILEGES IN SCHEMA ops_lab
GRANT
SELECT
    ON TABLES TO r_ops_readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA ops_lab
GRANT
SELECT
,
    INSERT,
UPDATE,
DELETE ON TABLES TO r_ops_rw;

-- 5) DDL用（今回は体験用にスキーマ作成権限のみ）
-- 本番で安易に与えるものではない、という前提で “概念体験”
GRANT CREATE ON DATABASE current_database() TO r_ops_ddl;

-- 6) 見える化
SELECT
    rolname,
    rolsuper,
    rolcreaterole,
    rolcreatedb,
    rolcanlogin
FROM
    pg_roles
WHERE
    rolname IN ('r_ops_readonly', 'r_ops_rw', 'r_ops_ddl')
ORDER BY
    rolname;

SELECT
    table_schema,
    table_name,
    privilege_type,
    grantee
FROM
    information_schema.role_table_grants
WHERE
    table_schema = 'ops_lab'
ORDER BY
    table_name,
    grantee,
    privilege_type;
